---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      memory: 1024
    network:
    - ["forwarded_port", {guest: 8080, host: 8080}]
    - ["forwarded_port", {guest: 4399, host: 4399}]

suites:
- name: default
  run_list:
  - recipe[apt]
  - recipe[chronos]
  attributes:
    chronos:
      jar_source: 'https://s3.amazonaws.com/dl.imedidata.net/chronos/chronos-2.1.0_mesos-0.14.0-rc4.jar'
      zookeeper_server_list: [54.221.163.45]
      zookeeper_port: 2181
      zookeeper_path: 'mesos-test'
      options:
        default_job_owner: 'rarodriguez@mdsol.com'
    mesos:
      version: '0.15.0'
